import { useState } from 'react'
import { api } from '../services/api'
import { useAsync } from '../hooks/useAsync'
import { Card, EmptyState, Loader } from '../components/ui'
import type { Statement } from '../data/types'
import { useAuth } from '../context/AuthContext'
import { formatDate } from '../utils/format'
import './pages.css'

const FILTERS = ['All', 'Monthly Statement', 'Trade Confirmation', 'Tax Document'] as const
type Filter = (typeof FILTERS)[number]

export default function DocumentsPage() {
  const { client } = useAuth()
  const { data, loading, error } = useAsync(() => api.getStatements(), [])
  const [filter, setFilter] = useState<Filter>('All')

  if (loading) return <Loader label="Opening your documents vault…" />
  if (error || !data) return <Card title="Unable to load">{error ?? 'Please try again.'}</Card>

  const docs = filter === 'All' ? data : data.filter((d) => d.type === filter)

  // Generate a placeholder document so the download button works in the
  // prototype. The real app streams the stored PDF from the backend.
  function download(doc: Statement) {
    const content = [
      'SIT INVEST — CLIENT STATEMENT',
      '================================',
      '',
      `Account holder: ${client?.name ?? ''}`,
      `Account number: ${client?.accountNumber ?? ''}`,
      `Document type:  ${doc.type}`,
      `Period:         ${doc.period}`,
      `Issued:         ${formatDate(doc.date)}`,
      '',
      'This is a sample document generated by the portal prototype.',
      'In production this downloads the official PDF from your records.',
    ].join('\n')
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `SitInvest_${doc.type.replace(/\s+/g, '')}_${doc.period.replace(/\s+/g, '')}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="stack">
      <div className="page-intro">
        <div>
          <h2>Documents Vault</h2>
          <p>
            Your monthly statements, trade confirmations and tax documents — securely stored
            and available to download any time.
          </p>
        </div>
      </div>

      <div className="doc-toolbar">
        {FILTERS.map((f) => (
          <button
            key={f}
            className={`chip-filter ${filter === f ? 'active' : ''}`}
            onClick={() => setFilter(f)}
          >
            {f === 'All' ? 'All documents' : `${f}s`}
          </button>
        ))}
      </div>

      {docs.length === 0 ? (
        <EmptyState>No documents in this category yet.</EmptyState>
      ) : (
        <div className="doc-grid">
          {docs.map((doc) => (
            <div key={doc.id} className="doc-card">
              <div className={`doc-icon ${iconClass(doc.type)}`}>
                <FileIcon />
              </div>
              <div className="doc-info">
                <div className="doc-period">{doc.period}</div>
                <div className="doc-meta">
                  {doc.type} · {formatDate(doc.date)} · {doc.sizeKb} KB
                </div>
              </div>
              <button
                className="doc-dl"
                aria-label={`Download ${doc.period} ${doc.type}`}
                onClick={() => download(doc)}
              >
                <DownloadIcon />
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

function iconClass(type: Statement['type']) {
  if (type === 'Tax Document') return 'tax'
  if (type === 'Trade Confirmation') return 'trade'
  return ''
}

function FileIcon() {
  return (
    <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8l-5-5Z" />
      <path d="M14 3v5h5" />
    </svg>
  )
}
function DownloadIcon() {
  return (
    <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M12 3v12" />
      <path d="m7 11 5 5 5-5" />
      <path d="M5 21h14" />
    </svg>
  )
}
